/* 最初から入っている単語・フレーズ。
   id は「カテゴリid-並び順」で自動で振る(例: stroller-3)。お気に入りや「覚えた」はこの id で保存するので、
   ★項目を足すときは各カテゴリの末尾に足し、途中への挿入・削除はしないこと(ずれると別の項目に付け替わる)。
   直すときは文言だけ書き換える。

   kind:"word"   の行 … [英語, 日本語, 品詞, 例文・英語, 例文・日本語, ひとことメモ(任意)]
   kind:"phrase" の行 … [英語, 日本語, ひとことメモ(任意)]
*/
const PHRASE_BOOK = [
  { id:"stroller", kind:"word", icon:"🛒", name:"ベビーカー", desc:"部位・機能・サイズの言葉", items:[
    ["stroller", "ベビーカー", "名詞", "This stroller is very light.", "このベビーカーはとても軽いです。", "「baby car」は和製英語で通じません。イギリスでは pushchair / pram とも言います。"],
    ["canopy", "幌（ほろ）・日よけ", "名詞", "Pull the canopy down to block the sun.", "幌を下ろすと日差しを防げます。"],
    ["handlebar", "ハンドル", "名詞", "The handlebar is height-adjustable.", "ハンドルは高さを調節できます。"],
    ["bumper bar", "フロントガード", "名詞", "The bumper bar can be removed.", "フロントガードは取り外せます。"],
    ["harness", "（安全）ベルト", "名詞", "Please fasten the harness.", "ベルトを締めてください。"],
    ["buckle", "バックル・留め具", "名詞", "Press the center of the buckle to open it.", "バックルの中央を押すと外れます。"],
    ["seat", "座席・シート", "名詞", "The seat is soft and wide.", "シートは柔らかくて広いです。"],
    ["backrest", "背もたれ", "名詞", "You can adjust the backrest.", "背もたれの角度を調節できます。"],
    ["footrest", "足のせ（フットレスト）", "名詞", "The footrest is adjustable, too.", "足のせも調節できます。"],
    ["wheels", "車輪・タイヤ", "名詞", "The wheels are large, so it's easy to push.", "車輪が大きいので押しやすいです。", "前輪は front wheels、後輪は rear wheels。"],
    ["brake", "ブレーキ", "名詞", "Step on this pedal to lock the brake.", "このペダルを踏むとブレーキがかかります。"],
    ["suspension", "サスペンション", "名詞", "The suspension absorbs bumps.", "サスペンションが段差の衝撃を吸収します。"],
    ["storage basket", "下カゴ（収納カゴ）", "名詞", "The storage basket is very large.", "下カゴはとても大きいです。"],
    ["frame", "フレーム（骨組み）", "名詞", "The frame is made of aluminum.", "フレームはアルミ製です。"],
    ["rain cover", "レインカバー", "名詞", "The rain cover is sold separately.", "レインカバーは別売りです。"],
    ["cup holder", "ドリンクホルダー", "名詞", "You can attach a cup holder here.", "ここにドリンクホルダーを付けられます。"],
    ["seat liner", "シートライナー（敷きパッド）", "名詞", "The seat liner keeps your baby cool.", "シートライナーで赤ちゃんが涼しく過ごせます。"],
    ["fold", "折りたたむ", "動詞", "You can fold it with one hand.", "片手で折りたためます。"],
    ["unfold", "広げる・開く", "動詞", "To unfold it, just pull the handlebar up.", "開くときは、ハンドルを引き上げるだけです。"],
    ["recline", "（背もたれを）倒す", "動詞", "The backrest reclines almost flat.", "背もたれはほぼフラットまで倒せます。"],
    ["push", "押す", "動詞", "Please try pushing it.", "押してみてください。"],
    ["attach", "取り付ける", "動詞", "You can attach a car seat to it.", "チャイルドシートを取り付けられます。"],
    ["lightweight", "軽量の", "形容詞", "This is our most lightweight model.", "こちらが一番軽いモデルです。"],
    ["compact", "コンパクトな", "形容詞", "It's compact when folded.", "たたむとコンパクトです。"],
    ["foldable", "折りたためる", "形容詞", "Is this stroller foldable?", "このベビーカーは折りたためますか？"],
    ["one-hand fold", "片手でたためること", "名詞", "The one-hand fold is very convenient.", "片手でたためるのがとても便利です。"],
    ["reversible", "対面・背面を切り替えられる", "形容詞", "The seat is reversible.", "シートは対面・背面を切り替えられます。", "対面＝parent-facing、背面＝forward-facing とも言います。"],
    ["adjustable", "調節できる", "形容詞", "The canopy is adjustable.", "幌は調節できます。"],
    ["detachable", "取り外せる", "形容詞", "The seat cover is detachable.", "シートカバーは取り外せます。"],
    ["washable", "洗える", "形容詞", "The seat cover is machine washable.", "シートカバーは洗濯機で洗えます。"],
    ["breathable", "通気性のよい", "形容詞", "The seat is breathable, so it stays cool.", "通気性がよく、蒸れにくいです。"],
    ["waterproof", "防水の", "形容詞", "The canopy is waterproof.", "幌は防水です。"],
    ["UV protection", "UVカット", "名詞", "The canopy has UV protection.", "幌はUVカット仕様です。"],
    ["durable", "丈夫な・長持ちする", "形容詞", "It's durable enough for a second child.", "2人目まで使えるほど丈夫です。"],
    ["stable", "安定した", "形容詞", "It's stable even on slopes.", "坂道でも安定しています。"],
    ["smooth", "なめらかな", "形容詞", "It has a smooth ride.", "乗り心地がなめらかです。"],
    ["padded", "クッション性のある", "形容詞", "The seat is thickly padded.", "シートは厚めのクッションです。"],
    ["cabin-size", "機内持ち込みサイズの", "形容詞", "This one is cabin-size on most airlines.", "こちらは多くの航空会社で機内持ち込みできるサイズです。", "航空会社によって規定が違うので「on most airlines」と添えると安心です。"],
    ["high seat", "ハイシート（座面が高い）", "名詞", "The high seat keeps your baby away from the heat of the ground.", "座面が高いので、地面からの熱から赤ちゃんを守れます。"],
    ["weight", "重さ", "名詞", "The weight is 4.9 kilograms.", "重さは4.9kgです。"],
    ["weigh", "重さが〜ある", "動詞", "It weighs about five kilograms.", "重さは約5kgです。", "5.5kg は「five point five kilograms」と読みます。"],
    ["width", "幅", "名詞", "It's narrow enough to go through ticket gates.", "改札を通れる幅です。"],
    ["folded size", "たたんだときのサイズ", "名詞", "The folded size is very small.", "たたんだときのサイズはとても小さいです。"],
    ["weight limit", "対象体重の上限", "名詞", "The weight limit is 22 kilograms.", "対象体重は22kgまでです。"],
    ["material", "素材", "名詞", "What material is this?", "これは何の素材ですか？"],
    ["aluminum", "アルミ", "名詞", "The frame is aluminum, so it's light.", "フレームがアルミなので軽いです。", "アメリカ英語は「アルーミナム」。イギリスでは aluminium（アルミニアム）。"],
    ["mesh", "メッシュ", "名詞", "The mesh window lets air in.", "メッシュの窓から風が通ります。"],
  ]},
  { id:"baby", kind:"word", icon:"👶", name:"赤ちゃん・ベビー用品", desc:"月齢・子育て・ほかの商品", items:[
    ["newborn", "新生児", "名詞", "It's suitable for newborns.", "新生児から使えます。"],
    ["infant", "乳児・赤ちゃん", "名詞", "It's designed for infants.", "乳児向けに作られています。"],
    ["toddler", "よちよち歩きの子（1〜3歳ごろ）", "名詞", "It's also good for toddlers.", "1〜3歳ごろの子にも使えます。"],
    ["months old", "生後〜か月", "フレーズ", "It can be used from one month old.", "生後1か月から使えます。", "お客さまからは「She's six months old.」のように返ってくることが多いです。"],
    ["due date", "出産予定日", "名詞", "When is your due date?", "出産予定日はいつですか？"],
    ["pregnant", "妊娠している", "形容詞", "She is five months pregnant.", "彼女は妊娠5か月です。"],
    ["twins", "双子", "名詞", "We have a double stroller for twins.", "双子用の2人乗りベビーカーがございます。"],
    ["sit up", "お座りする", "動詞", "Can your baby sit up on their own?", "お子さまはひとりでお座りできますか？", "B型ベビーカーの説明で使います。"],
    ["grow", "成長する", "動詞", "You can use it as your baby grows.", "お子さまの成長に合わせて使えます。"],
    ["diaper", "おむつ", "名詞", "There's a diaper-changing table in the restroom.", "お手洗いにおむつ交換台がございます。", "イギリスでは nappy。"],
    ["formula", "粉ミルク", "名詞", "We have hot water for formula.", "ミルク用のお湯がございます。"],
    ["baby bottle", "哺乳びん", "名詞", "There's a pocket for a baby bottle.", "哺乳びんを入れるポケットがあります。"],
    ["pacifier", "おしゃぶり", "名詞", "You can hang a pacifier clip here.", "ここにおしゃぶりホルダーを付けられます。", "イギリスでは dummy。"],
    ["nursing room", "授乳室", "名詞", "The nursing room is on the second floor.", "授乳室は2階にございます。"],
    ["nap", "お昼寝", "名詞", "Your baby can take a nap in it.", "赤ちゃんがこの中でお昼寝できます。"],
    ["car seat", "チャイルドシート", "名詞", "This car seat fits this stroller.", "このチャイルドシートはこのベビーカーに取り付けられます。"],
    ["baby carrier", "抱っこひも", "名詞", "Many parents use a baby carrier, too.", "抱っこひもを併用する方も多いです。"],
    ["crib", "ベビーベッド", "名詞", "We also sell cribs.", "ベビーベッドも取り扱っています。", "イギリスでは cot。"],
    ["high chair", "ベビーチェア（食事用）", "名詞", "The high chairs are over there.", "食事用のベビーチェアはあちらです。"],
    ["bouncer", "バウンサー", "名詞", "Babies love this bouncer.", "赤ちゃんはこのバウンサーが大好きです。"],
    ["bib", "よだれかけ・スタイ", "名詞", "Bibs are sold in sets of three.", "スタイは3枚セットで販売しています。"],
    ["blanket", "ブランケット", "名詞", "You can clip a blanket here.", "ここにブランケットを留められます。"],
    ["safety standard", "安全基準", "名詞", "It meets Japanese safety standards.", "日本の安全基準を満たしています。"],
  ]},
  { id:"shop", kind:"word", icon:"🛍️", name:"お店・お会計", desc:"在庫・値段・免税・配送", items:[
    ["price", "価格・値段", "名詞", "The price includes tax.", "価格は税込みです。"],
    ["including tax", "税込み", "フレーズ", "It's 65,000 yen, including tax.", "税込みで65,000円です。", "65,000 は sixty-five thousand と読みます。"],
    ["tax-free", "免税の", "形容詞", "You can buy it tax-free.", "免税でお買い求めいただけます。"],
    ["passport", "パスポート", "名詞", "May I see your passport, please?", "パスポートを拝見してもよろしいですか？", "免税手続きで必ず使います。"],
    ["on sale", "セール中・値下げ中", "フレーズ", "This model is on sale this week.", "このモデルは今週セール中です。"],
    ["discount", "割引", "名詞", "I'm sorry, we can't offer a discount.", "申し訳ございませんが、値引きはいたしかねます。"],
    ["credit card", "クレジットカード", "名詞", "We accept credit cards.", "クレジットカードがお使いいただけます。"],
    ["receipt", "レシート・領収書", "名詞", "Here's your receipt.", "レシートでございます。", "p は発音しません（リシート）。"],
    ["in stock", "在庫あり", "フレーズ", "Let me check if we have it in stock.", "在庫を確認いたします。"],
    ["out of stock", "在庫切れ", "フレーズ", "I'm sorry, it's out of stock right now.", "申し訳ございません、ただいま在庫切れです。"],
    ["sold out", "売り切れ", "フレーズ", "The limited color is sold out.", "限定色は売り切れです。"],
    ["color", "色", "名詞", "It comes in three colors.", "3色からお選びいただけます。", "イギリスでは colour。"],
    ["model", "機種・モデル", "名詞", "This is our most popular model.", "こちらが一番人気のモデルです。"],
    ["limited edition", "限定版", "名詞", "This is a limited edition color.", "こちらは限定カラーです。"],
    ["display model", "展示品", "名詞", "This is the display model.", "こちらは展示品です。"],
    ["brand-new", "新品の", "形容詞", "We'll give you a brand-new one.", "新品をお渡しします。"],
    ["warranty", "保証", "名詞", "It comes with a one-year warranty.", "1年間の保証が付いています。"],
    ["instruction manual", "取扱説明書", "名詞", "The instruction manual is also in English.", "取扱説明書は英語版もございます。"],
    ["sold separately", "別売り", "フレーズ", "The rain cover is sold separately.", "レインカバーは別売りです。"],
    ["gift wrapping", "ギフト包装", "名詞", "Would you like gift wrapping?", "ギフト包装はいかがなさいますか？"],
    ["delivery", "配達", "名詞", "We can deliver it to your hotel.", "ホテルまでお届けできます。"],
    ["ship overseas", "海外へ発送する", "フレーズ", "I'm sorry, we can't ship overseas.", "申し訳ございません、海外発送は承っておりません。"],
    ["exchange", "交換", "名詞", "We can do an exchange within one week.", "1週間以内なら交換できます。"],
    ["refund", "返金", "名詞", "I'm sorry, we can't give a refund.", "申し訳ございませんが、返金はできかねます。"],
  ]},
  { id:"phrase", kind:"phrase", icon:"💬", name:"接客のひと言", desc:"まずはこれだけ言えればOK", items:[
    ["Hello! Welcome.", "いらっしゃいませ。", "目を見て笑顔で「Hello!」と言うのが自然です。"],
    ["Please take your time.", "ごゆっくりご覧ください。"],
    ["Are you looking for anything in particular?", "何かお探しですか？"],
    ["How old is your baby?", "お子さまは何か月（何歳）ですか？"],
    ["How will you mainly use it?", "主にどんな場面で使う予定ですか？"],
    ["I'd recommend this one.", "こちらがおすすめです。"],
    ["Would you like to try it?", "試してみますか？"],
    ["Let me show you how to fold it.", "たたみ方をお見せしますね。"],
    ["Let me check if we have it in stock.", "在庫を確認いたします。"],
    ["Just a moment, please.", "少々お待ちください。"],
    ["Sorry, could you say that again?", "すみません、もう一度おっしゃっていただけますか？"],
    ["Could you speak a little more slowly?", "もう少しゆっくり話していただけますか？"],
    ["You can buy it tax-free.", "免税でお買い求めいただけます。"],
    ["May I see your passport, please?", "パスポートを拝見してもよろしいですか？"],
    ["How would you like to pay?", "お支払い方法はいかがなさいますか？"],
    ["Here's your receipt.", "レシートでございます。"],
    ["What a cute baby!", "かわいい赤ちゃんですね！"],
    ["Does that make sense?", "おわかりいただけましたか？", "「Do you understand?」は上から目線に聞こえることがあるので、こちらが無難です。"],
    ["Thank you very much.", "ありがとうございました。"],
    ["Have a nice trip!", "よいご旅行を！"],
  ]},
];

/* 例文(フレーズは本文)の語句の解説。id は上と同じ「カテゴリid-並び順」。
   「語句＝意味」を「｜」で区切って並べる。一覧で例文を開いたときと、フラッシュカードの裏に出る。 */
const PHRASE_NOTES = {
  "stroller-1": "this stroller＝このベビーカー｜very＝とても｜light＝軽い（重さが「軽い」。明るさの light と同じつづり）",
  "stroller-2": "pull 〜 down＝〜を引き下ろす｜block＝さえぎる｜the sun＝日差し",
  "stroller-3": "height＝高さ（ハイト）｜-adjustable＝〜を調節できる｜height-adjustable＝高さを調節できる",
  "stroller-4": "can be removed＝取り外せる（can be ＋過去分詞＝〜できる）｜remove＝取り外す",
  "stroller-5": "Please 〜＝〜してください（丁寧なお願い）｜fasten＝（ベルトを）締める。t は発音しない（ファスン）",
  "stroller-6": "press＝押す｜the center of 〜＝〜の真ん中｜to open it＝それを開けるには（to ＝〜するために）",
  "stroller-7": "soft＝柔らかい｜wide＝広い（幅が広い）",
  "stroller-8": "You can 〜＝〜できます（機能の説明で一番使う形）｜adjust＝調節する",
  "stroller-9": "adjustable＝調節できる｜, too＝〜も（文の最後に付ける）",
  "stroller-10": "large＝大きい｜so＝だから｜it's easy to 〜＝〜しやすい",
  "stroller-11": "step on 〜＝〜を踏む｜pedal＝ペダル｜lock＝固定する・かける",
  "stroller-12": "absorb＝吸収する｜bump＝段差・でこぼこ（複数形 bumps）",
  "stroller-13": "storage＝収納｜basket＝カゴ｜very large＝とても大きい",
  "stroller-14": "be made of 〜＝〜でできている｜aluminum＝アルミ（アメリカ英語はアルーミナム）",
  "stroller-15": "sold separately＝別売り（sold は sell「売る」の過去分詞）",
  "stroller-16": "attach＝取り付ける｜here＝ここに",
  "stroller-17": "keep A cool＝A を涼しく保つ｜your baby＝お子さま（お客さまの赤ちゃん）",
  "stroller-18": "fold＝折りたたむ｜with one hand＝片手で",
  "stroller-19": "To 〜＝〜するには（文の最初に置く）｜just＝〜するだけ｜pull 〜 up＝〜を引き上げる",
  "stroller-20": "recline＝（背もたれが）倒れる｜almost＝ほとんど｜flat＝平ら",
  "stroller-21": "try ～ing＝試しに〜してみる｜push＝押す",
  "stroller-22": "attach A to B＝A を B に取り付ける｜car seat＝チャイルドシート",
  "stroller-23": "our most 〜 model＝うちで一番〜なモデル｜lightweight＝軽量の",
  "stroller-24": "compact＝コンパクトな｜when folded＝たたんだとき（when it is folded の省略）",
  "stroller-25": "Is this 〜?＝これは〜ですか？｜foldable＝折りたためる（-able＝〜できる）",
  "stroller-26": "one-hand fold＝片手でたためること｜convenient＝便利な",
  "stroller-27": "reversible＝向きを逆にできる（対面・背面の切り替え）",
  "stroller-28": "adjustable＝調節できる｜canopy＝幌（ほろ）",
  "stroller-29": "seat cover＝シートカバー｜detachable＝取り外せる（detach＝外す）",
  "stroller-30": "machine washable＝洗濯機で洗える（machine＝洗濯機のこと）",
  "stroller-31": "breathable＝通気性のよい（breathe＝呼吸する）｜so＝だから｜stay cool＝涼しいままでいる",
  "stroller-32": "waterproof＝防水の（-proof＝〜を通さない）",
  "stroller-33": "has＝〜が付いている｜UV protection＝紫外線カット",
  "stroller-34": "durable＝丈夫な｜enough for 〜＝〜にも十分なほど｜a second child＝2人目のお子さま",
  "stroller-35": "stable＝安定した｜even＝〜でさえ｜slope＝坂（複数形 slopes）",
  "stroller-36": "It has a 〜 ride.＝乗り心地が〜です｜smooth＝なめらかな",
  "stroller-37": "thickly＝厚く｜padded＝クッションが入った",
  "stroller-38": "cabin-size＝機内に持ち込めるサイズ｜on most airlines＝ほとんどの航空会社で",
  "stroller-39": "keep A away from B＝A を B から離しておく｜the heat of the ground＝地面の熱",
  "stroller-40": "weight＝重さ｜4.9 は four point nine と読む｜kilogram＝キログラム",
  "stroller-41": "weigh＝重さが〜ある（weight の動詞）｜about＝約",
  "stroller-42": "narrow＝幅がせまい｜enough to 〜＝〜できるほど｜go through＝通り抜ける｜ticket gate＝改札",
  "stroller-43": "folded size＝たたんだときのサイズ｜very small＝とても小さい",
  "stroller-44": "weight limit＝重さの上限（ここではお子さまの体重）｜22 は twenty-two",
  "stroller-45": "What 〜 is this?＝これは何の〜ですか？｜material＝素材",
  "stroller-46": "aluminum＝アルミ｜so＝だから｜light＝軽い",
  "stroller-47": "mesh window＝メッシュの窓｜let A in＝A を中に入れる｜air＝空気・風",
  "baby-1": "suitable for 〜＝〜に向いている・使える｜newborn＝新生児",
  "baby-2": "be designed for 〜＝〜向けに作られている｜infant＝乳児",
  "baby-3": "also＝〜も｜be good for 〜＝〜に向いている｜toddler＝よちよち歩きの子",
  "baby-4": "can be used＝使える（can be ＋過去分詞）｜from 〜＝〜から｜one month old＝生後1か月",
  "baby-5": "When is 〜?＝〜はいつですか？｜due date＝出産予定日",
  "baby-6": "five months pregnant＝妊娠5か月（数字＋months＋pregnant の順）",
  "baby-7": "We have 〜＝（お店に）〜がございます｜double stroller＝2人乗りベビーカー｜twins＝双子",
  "baby-8": "Can your baby 〜?＝お子さまは〜できますか？｜sit up＝お座りする｜on their own＝ひとりで",
  "baby-9": "as＝〜につれて｜grow＝成長する",
  "baby-10": "There's 〜＝〜があります（There is の短縮）｜diaper-changing table＝おむつ交換台｜restroom＝お手洗い",
  "baby-11": "hot water＝お湯（hot で「熱い水」＝お湯）｜formula＝粉ミルク",
  "baby-12": "pocket＝ポケット｜for 〜＝〜を入れるための｜baby bottle＝哺乳びん",
  "baby-13": "hang＝つり下げる・かける｜pacifier clip＝おしゃぶりホルダー",
  "baby-14": "nursing room＝授乳室｜on the second floor＝2階に（階は on を使う）",
  "baby-15": "take a nap＝お昼寝する｜in it＝その中で",
  "baby-16": "fit＝ぴったり合う・取り付けられる｜this stroller＝このベビーカー",
  "baby-17": "many parents＝多くの親御さん｜baby carrier＝抱っこひも｜, too＝〜も",
  "baby-18": "We also sell 〜＝〜も販売しています｜crib＝ベビーベッド",
  "baby-19": "high chair＝食事用のベビーチェア｜over there＝あちらに",
  "baby-20": "Babies love 〜＝赤ちゃんは〜が大好きです｜bouncer＝バウンサー",
  "baby-21": "be sold in sets of 〜＝〜個セットで売られている｜bib＝よだれかけ",
  "baby-22": "clip＝（クリップで）留める｜blanket＝ブランケット",
  "baby-23": "meet＝（基準を）満たす｜safety standards＝安全基準",
  "shop-1": "price＝価格｜include＝含む｜tax＝税",
  "shop-2": "65,000 は sixty-five thousand と読む｜including tax＝税込みで",
  "shop-3": "You can 〜＝〜できます｜buy it tax-free＝免税で買う",
  "shop-4": "May I 〜?＝〜してもよろしいですか？（とても丁寧）｜passport＝パスポート",
  "shop-5": "be on sale＝セール中｜this week＝今週",
  "shop-6": "I'm sorry＝申し訳ございません｜can't offer＝ご提供できない｜discount＝割引",
  "shop-7": "accept＝（支払い方法を）受け付ける｜credit cards＝クレジットカード",
  "shop-8": "Here's 〜＝こちらが〜です（物を渡すとき）｜receipt＝レシート（p は読まない）",
  "shop-9": "Let me 〜＝〜させてください・〜しますね｜check if 〜＝〜かどうか確認する｜in stock＝在庫がある",
  "shop-10": "out of stock＝在庫切れ｜right now＝ただいま",
  "shop-11": "limited color＝限定色｜sold out＝売り切れ",
  "shop-12": "come in 〜＝（色・サイズが）〜で展開している｜three colors＝3色",
  "shop-13": "our most popular 〜＝一番人気の〜｜model＝モデル",
  "shop-14": "limited edition＝限定版｜color＝色",
  "shop-15": "display model＝展示品｜This is 〜＝こちらは〜です",
  "shop-16": "We'll give you 〜＝〜をお渡しします（We will の短縮）｜brand-new＝新品の",
  "shop-17": "come with 〜＝〜が付いている｜one-year＝1年間の｜warranty＝保証",
  "shop-18": "instruction manual＝取扱説明書｜also＝〜も｜in English＝英語で",
  "shop-19": "sold separately＝別売り｜rain cover＝レインカバー",
  "shop-20": "Would you like 〜?＝〜はいかがですか？（丁寧にすすめる）｜gift wrapping＝ギフト包装",
  "shop-21": "deliver A to B＝A を B に届ける｜hotel＝ホテル",
  "shop-22": "ship＝発送する（船に限らない）｜overseas＝海外へ",
  "shop-23": "do an exchange＝交換する｜within one week＝1週間以内に",
  "shop-24": "give a refund＝返金する｜can't＝できない",
  "phrase-1": "Welcome.＝いらっしゃいませ（Hello! と一緒に笑顔で）",
  "phrase-2": "take your time＝ごゆっくりどうぞ（直訳：時間をかけてください）",
  "phrase-3": "look for 〜＝〜を探す｜anything in particular＝特に何か",
  "phrase-4": "How old 〜?＝何歳（何か月）ですか？｜答えは He's 〜 months old. など",
  "phrase-5": "How will you 〜?＝どのように〜しますか？｜mainly＝主に｜use＝使う",
  "phrase-6": "I'd recommend 〜＝〜をおすすめします（I would の短縮。やわらかい言い方）｜this one＝こちら",
  "phrase-7": "Would you like to 〜?＝〜してみませんか？（丁寧なすすめ）｜try＝試す",
  "phrase-8": "Let me show you 〜＝〜をお見せしますね｜how to 〜＝〜のしかた｜fold＝たたむ",
  "phrase-9": "Let me check＝確認しますね｜if 〜＝〜かどうか｜in stock＝在庫がある",
  "phrase-10": "Just a moment＝少々お待ちください｜please を付けると丁寧",
  "phrase-11": "Could you 〜?＝〜していただけますか？（丁寧なお願い）｜say that again＝もう一度言う",
  "phrase-12": "a little more slowly＝もう少しゆっくり｜speak＝話す",
  "phrase-13": "You can 〜＝〜できます｜buy it tax-free＝免税で買う",
  "phrase-14": "May I see 〜?＝〜を拝見してもよろしいですか？｜passport＝パスポート",
  "phrase-15": "How would you like to pay?＝お支払い方法はいかがなさいますか？（決まり文句）",
  "phrase-16": "Here's 〜＝こちらが〜です（物を渡すとき）｜receipt＝レシート",
  "phrase-17": "What a 〜!＝なんて〜なんでしょう！｜cute＝かわいい",
  "phrase-18": "make sense＝意味が通じる・わかる｜Does that 〜?＝それは〜ですか？",
  "phrase-19": "Thank you very much.＝ありがとうございました（very much で丁寧に）",
  "phrase-20": "Have a nice 〜!＝よい〜を！｜trip＝旅行（day にすると「よい一日を」）"
};

/* 言い換え(覚えにくい・言いにくいときに使える、やさしい言い方)。id は上と同じ「カテゴリid-並び順」。
   言い換えを「｜」で区切って並べる。（ ）の中は日本語のメモ。言い換えが自然にできるものだけに付けている。 */
const PHRASE_ALTS = {
  "stroller-1": "pushchair（イギリス英語）｜buggy（イギリス英語。軽いタイプ）",
  "stroller-2": "sunshade（日よけ）｜sun cover",
  "stroller-3": "handle（そのまま通じる）",
  "stroller-4": "front bar｜safety bar",
  "stroller-5": "seat belt｜belt",
  "stroller-6": "clip",
  "stroller-8": "back of the seat",
  "stroller-9": "leg rest",
  "stroller-13": "basket｜bottom basket",
  "stroller-15": "rain shield",
  "stroller-16": "drink holder",
  "stroller-17": "seat pad｜cushion",
  "stroller-18": "fold up｜close（「たたむ」をやさしく）",
  "stroller-19": "open（「開く」をやさしく）",
  "stroller-20": "lean back｜lay back",
  "stroller-22": "put on｜connect",
  "stroller-23": "light（軽い）",
  "stroller-24": "small（小さい）",
  "stroller-25": "can fold（たためる）",
  "stroller-26": "fold with one hand",
  "stroller-27": "can face both ways（両方向に向けられる）",
  "stroller-28": "can change（変えられる）",
  "stroller-29": "removable｜can take off（外せる）",
  "stroller-30": "can wash（洗える）",
  "stroller-31": "airy（風通しがいい）｜lets air through",
  "stroller-32": "keeps water out（水を通さない）",
  "stroller-33": "sun protection｜blocks UV rays",
  "stroller-34": "strong（丈夫）｜lasts a long time（長持ち）",
  "stroller-35": "steady（ぐらつかない）",
  "stroller-36": "not bumpy（ガタガタしない）",
  "stroller-37": "soft（やわらかい）｜cushioned",
  "stroller-38": "small enough for the plane（飛行機に持ち込める大きさ）",
  "stroller-39": "tall seat",
  "stroller-42": "how wide（どのくらいの幅か）",
  "stroller-43": "size when folded",
  "stroller-44": "maximum weight｜up to 22 kilograms（22kgまで）",
  "stroller-45": "what it's made of（何でできているか）",
  "stroller-47": "net fabric（網の生地）",
  "baby-1": "new baby",
  "baby-2": "baby",
  "baby-3": "little kid｜small child",
  "baby-5": "when the baby is coming（いつ生まれるか）",
  "baby-6": "expecting（妊娠中。やわらかい言い方）｜having a baby",
  "baby-8": "sit by themselves",
  "baby-9": "get bigger（大きくなる）",
  "baby-10": "nappy（イギリス英語）",
  "baby-11": "baby milk｜powdered milk",
  "baby-12": "bottle",
  "baby-13": "dummy（イギリス英語）｜binky（アメリカの口語）",
  "baby-14": "baby room｜feeding room",
  "baby-15": "sleep｜rest",
  "baby-16": "baby car seat",
  "baby-17": "carrier｜baby sling（布のタイプ）",
  "baby-18": "baby bed｜cot（イギリス英語）",
  "baby-19": "baby chair｜feeding chair",
  "baby-20": "baby rocker",
  "baby-23": "safety rules",
  "shop-1": "cost（値段）",
  "shop-2": "tax included｜with tax",
  "shop-3": "without tax（税なしで）",
  "shop-5": "discounted（値下げ中）",
  "shop-6": "price cut｜percent off（〜%オフ）",
  "shop-7": "card",
  "shop-9": "available（あります）｜we have it",
  "shop-10": "not available now｜we don't have it now",
  "shop-11": "all gone（全部なくなった）",
  "shop-13": "type（種類）",
  "shop-14": "special edition",
  "shop-15": "floor model｜sample",
  "shop-16": "new｜unused（未使用）",
  "shop-17": "guarantee（保証）",
  "shop-18": "manual｜how-to guide",
  "shop-19": "not included（含まれていない）｜extra",
  "shop-20": "gift wrap",
  "shop-21": "send（送る）",
  "shop-22": "send abroad（海外へ送る）",
  "shop-23": "swap（取り替える）",
  "shop-24": "money back（お金を返す）",
  "phrase-1": "Hi! Come on in.",
  "phrase-2": "No rush.（急がなくて大丈夫です）",
  "phrase-3": "Can I help you find something?｜What are you looking for?",
  "phrase-4": "How many months is your baby?",
  "phrase-5": "Where will you use it most?",
  "phrase-6": "This one is good.｜I like this one.",
  "phrase-7": "Do you want to try it?",
  "phrase-8": "I'll show you how to fold it.",
  "phrase-9": "I'll check if we have it.",
  "phrase-10": "One moment, please.｜Just a second.",
  "phrase-11": "Sorry?｜Pardon?",
  "phrase-12": "Slowly, please.",
  "phrase-13": "You don't have to pay tax.",
  "phrase-14": "Passport, please.",
  "phrase-15": "Cash or card?",
  "phrase-16": "Your receipt.",
  "phrase-17": "Your baby is so cute!",
  "phrase-18": "Is that OK?｜Is that clear?",
  "phrase-19": "Thanks a lot.",
  "phrase-20": "Enjoy your trip!"
};
