/* 最初から入っている単語・フレーズ。
   id は「カテゴリid-並び順」で自動で振る(例: stroller-3)。お気に入りや「覚えた」はこの id で保存するので、
   ★項目を足すときは各カテゴリの末尾に足し、途中への挿入・削除はしないこと(ずれると別の項目に付け替わる)。
   直すときは文言だけ書き換える。

   kind:"word"   の行 … [英語, 日本語, 品詞, 例文・英語, 例文・日本語, ひとことメモ(任意)]
   kind:"phrase" の行 … [英語, 日本語, ひとことメモ(任意)]
*/
const PHRASE_BOOK = [
  { id:"stroller", kind:"word", icon:"🛒", name:"ベビーカー", desc:"部位・機能・サイズの言葉", items:[
    ["stroller", "ベビーカー", "名詞", "This stroller is very light.", "このベビーカーはとても軽いです。", "「baby car」は和製英語で通じません。イギリスでは pushchair / pram とも言います。"],
    ["canopy", "幌（ほろ）・日よけ", "名詞", "Pull the canopy down to block the sun.", "幌を下ろすと日差しを防げます。"],
    ["handlebar", "ハンドル", "名詞", "The handlebar is height-adjustable.", "ハンドルは高さを調節できます。"],
    ["bumper bar", "フロントガード", "名詞", "The bumper bar can be removed.", "フロントガードは取り外せます。"],
    ["harness", "（安全）ベルト", "名詞", "Please fasten the harness.", "ベルトを締めてください。"],
    ["buckle", "バックル・留め具", "名詞", "Press the center of the buckle to open it.", "バックルの中央を押すと外れます。"],
    ["seat", "座席・シート", "名詞", "The seat is soft and wide.", "シートは柔らかくて広いです。"],
    ["backrest", "背もたれ", "名詞", "You can adjust the backrest.", "背もたれの角度を調節できます。"],
    ["footrest", "足のせ（フットレスト）", "名詞", "The footrest is adjustable, too.", "足のせも調節できます。"],
    ["wheels", "車輪・タイヤ", "名詞", "The wheels are large, so it's easy to push.", "車輪が大きいので押しやすいです。", "前輪は front wheels、後輪は rear wheels。"],
    ["brake", "ブレーキ", "名詞", "Step on this pedal to lock the brake.", "このペダルを踏むとブレーキがかかります。"],
    ["suspension", "サスペンション", "名詞", "The suspension absorbs bumps.", "サスペンションが段差の衝撃を吸収します。"],
    ["storage basket", "下カゴ（収納カゴ）", "名詞", "The storage basket is very large.", "下カゴはとても大きいです。"],
    ["frame", "フレーム（骨組み）", "名詞", "The frame is made of aluminum.", "フレームはアルミ製です。"],
    ["rain cover", "レインカバー", "名詞", "The rain cover is sold separately.", "レインカバーは別売りです。"],
    ["cup holder", "ドリンクホルダー", "名詞", "You can attach a cup holder here.", "ここにドリンクホルダーを付けられます。"],
    ["seat liner", "シートライナー（敷きパッド）", "名詞", "The seat liner keeps your baby cool.", "シートライナーで赤ちゃんが涼しく過ごせます。"],
    ["fold", "折りたたむ", "動詞", "You can fold it with one hand.", "片手で折りたためます。"],
    ["unfold", "広げる・開く", "動詞", "To unfold it, just pull the handlebar up.", "開くときは、ハンドルを引き上げるだけです。"],
    ["recline", "（背もたれを）倒す", "動詞", "The backrest reclines almost flat.", "背もたれはほぼフラットまで倒せます。"],
    ["push", "押す", "動詞", "Please try pushing it.", "押してみてください。"],
    ["attach", "取り付ける", "動詞", "You can attach a car seat to it.", "チャイルドシートを取り付けられます。"],
    ["lightweight", "軽量の", "形容詞", "This is our most lightweight model.", "こちらが一番軽いモデルです。"],
    ["compact", "コンパクトな", "形容詞", "It's compact when folded.", "たたむとコンパクトです。"],
    ["foldable", "折りたためる", "形容詞", "Is this stroller foldable?", "このベビーカーは折りたためますか？"],
    ["one-hand fold", "片手でたためること", "名詞", "The one-hand fold is very convenient.", "片手でたためるのがとても便利です。"],
    ["reversible", "対面・背面を切り替えられる", "形容詞", "The seat is reversible.", "シートは対面・背面を切り替えられます。", "対面＝parent-facing、背面＝forward-facing とも言います。"],
    ["adjustable", "調節できる", "形容詞", "The canopy is adjustable.", "幌は調節できます。"],
    ["detachable", "取り外せる", "形容詞", "The seat cover is detachable.", "シートカバーは取り外せます。"],
    ["washable", "洗える", "形容詞", "The seat cover is machine washable.", "シートカバーは洗濯機で洗えます。"],
    ["breathable", "通気性のよい", "形容詞", "The seat is breathable, so it stays cool.", "通気性がよく、蒸れにくいです。"],
    ["waterproof", "防水の", "形容詞", "The canopy is waterproof.", "幌は防水です。"],
    ["UV protection", "UVカット", "名詞", "The canopy has UV protection.", "幌はUVカット仕様です。"],
    ["durable", "丈夫な・長持ちする", "形容詞", "It's durable enough for a second child.", "2人目まで使えるほど丈夫です。"],
    ["stable", "安定した", "形容詞", "It's stable even on slopes.", "坂道でも安定しています。"],
    ["smooth", "なめらかな", "形容詞", "It has a smooth ride.", "乗り心地がなめらかです。"],
    ["padded", "クッション性のある", "形容詞", "The seat is thickly padded.", "シートは厚めのクッションです。"],
    ["cabin-size", "機内持ち込みサイズの", "形容詞", "This one is cabin-size on most airlines.", "こちらは多くの航空会社で機内持ち込みできるサイズです。", "航空会社によって規定が違うので「on most airlines」と添えると安心です。"],
    ["high seat", "ハイシート（座面が高い）", "名詞", "The high seat keeps your baby away from the heat of the ground.", "座面が高いので、地面からの熱から赤ちゃんを守れます。"],
    ["weight", "重さ", "名詞", "The weight is 4.9 kilograms.", "重さは4.9kgです。"],
    ["weigh", "重さが〜ある", "動詞", "It weighs about five kilograms.", "重さは約5kgです。", "5.5kg は「five point five kilograms」と読みます。"],
    ["width", "幅", "名詞", "It's narrow enough to go through ticket gates.", "改札を通れる幅です。"],
    ["folded size", "たたんだときのサイズ", "名詞", "The folded size is very small.", "たたんだときのサイズはとても小さいです。"],
    ["weight limit", "対象体重の上限", "名詞", "The weight limit is 22 kilograms.", "対象体重は22kgまでです。"],
    ["material", "素材", "名詞", "What material is this?", "これは何の素材ですか？"],
    ["aluminum", "アルミ", "名詞", "The frame is aluminum, so it's light.", "フレームがアルミなので軽いです。", "アメリカ英語は「アルーミナム」。イギリスでは aluminium（アルミニアム）。"],
    ["mesh", "メッシュ", "名詞", "The mesh window lets air in.", "メッシュの窓から風が通ります。"],
  ]},
  { id:"baby", kind:"word", icon:"👶", name:"赤ちゃん・ベビー用品", desc:"月齢・子育て・ほかの商品", items:[
    ["newborn", "新生児", "名詞", "It's suitable for newborns.", "新生児から使えます。"],
    ["infant", "乳児・赤ちゃん", "名詞", "It's designed for infants.", "乳児向けに作られています。"],
    ["toddler", "よちよち歩きの子（1〜3歳ごろ）", "名詞", "It's also good for toddlers.", "1〜3歳ごろの子にも使えます。"],
    ["months old", "生後〜か月", "フレーズ", "It can be used from one month old.", "生後1か月から使えます。", "お客さまからは「She's six months old.」のように返ってくることが多いです。"],
    ["due date", "出産予定日", "名詞", "When is your due date?", "出産予定日はいつですか？"],
    ["pregnant", "妊娠している", "形容詞", "She is five months pregnant.", "彼女は妊娠5か月です。"],
    ["twins", "双子", "名詞", "We have a double stroller for twins.", "双子用の2人乗りベビーカーがございます。"],
    ["sit up", "お座りする", "動詞", "Can your baby sit up on their own?", "お子さまはひとりでお座りできますか？", "B型ベビーカーの説明で使います。"],
    ["grow", "成長する", "動詞", "You can use it as your baby grows.", "お子さまの成長に合わせて使えます。"],
    ["diaper", "おむつ", "名詞", "There's a diaper-changing table in the restroom.", "お手洗いにおむつ交換台がございます。", "イギリスでは nappy。"],
    ["formula", "粉ミルク", "名詞", "We have hot water for formula.", "ミルク用のお湯がございます。"],
    ["baby bottle", "哺乳びん", "名詞", "There's a pocket for a baby bottle.", "哺乳びんを入れるポケットがあります。"],
    ["pacifier", "おしゃぶり", "名詞", "You can hang a pacifier clip here.", "ここにおしゃぶりホルダーを付けられます。", "イギリスでは dummy。"],
    ["nursing room", "授乳室", "名詞", "The nursing room is on the second floor.", "授乳室は2階にございます。"],
    ["nap", "お昼寝", "名詞", "Your baby can take a nap in it.", "赤ちゃんがこの中でお昼寝できます。"],
    ["car seat", "チャイルドシート", "名詞", "This car seat fits this stroller.", "このチャイルドシートはこのベビーカーに取り付けられます。"],
    ["baby carrier", "抱っこひも", "名詞", "Many parents use a baby carrier, too.", "抱っこひもを併用する方も多いです。"],
    ["crib", "ベビーベッド", "名詞", "We also sell cribs.", "ベビーベッドも取り扱っています。", "イギリスでは cot。"],
    ["high chair", "ベビーチェア（食事用）", "名詞", "The high chairs are over there.", "食事用のベビーチェアはあちらです。"],
    ["bouncer", "バウンサー", "名詞", "Babies love this bouncer.", "赤ちゃんはこのバウンサーが大好きです。"],
    ["bib", "よだれかけ・スタイ", "名詞", "Bibs are sold in sets of three.", "スタイは3枚セットで販売しています。"],
    ["blanket", "ブランケット", "名詞", "You can clip a blanket here.", "ここにブランケットを留められます。"],
    ["safety standard", "安全基準", "名詞", "It meets Japanese safety standards.", "日本の安全基準を満たしています。"],
  ]},
  { id:"shop", kind:"word", icon:"🛍️", name:"お店・お会計", desc:"在庫・値段・免税・配送", items:[
    ["price", "価格・値段", "名詞", "The price includes tax.", "価格は税込みです。"],
    ["including tax", "税込み", "フレーズ", "It's 65,000 yen, including tax.", "税込みで65,000円です。", "65,000 は sixty-five thousand と読みます。"],
    ["tax-free", "免税の", "形容詞", "You can buy it tax-free.", "免税でお買い求めいただけます。"],
    ["passport", "パスポート", "名詞", "May I see your passport, please?", "パスポートを拝見してもよろしいですか？", "免税手続きで必ず使います。"],
    ["on sale", "セール中・値下げ中", "フレーズ", "This model is on sale this week.", "このモデルは今週セール中です。"],
    ["discount", "割引", "名詞", "I'm sorry, we can't offer a discount.", "申し訳ございませんが、値引きはいたしかねます。"],
    ["credit card", "クレジットカード", "名詞", "We accept credit cards.", "クレジットカードがお使いいただけます。"],
    ["receipt", "レシート・領収書", "名詞", "Here's your receipt.", "レシートでございます。", "p は発音しません（リシート）。"],
    ["in stock", "在庫あり", "フレーズ", "Let me check if we have it in stock.", "在庫を確認いたします。"],
    ["out of stock", "在庫切れ", "フレーズ", "I'm sorry, it's out of stock right now.", "申し訳ございません、ただいま在庫切れです。"],
    ["sold out", "売り切れ", "フレーズ", "The limited color is sold out.", "限定色は売り切れです。"],
    ["color", "色", "名詞", "It comes in three colors.", "3色からお選びいただけます。", "イギリスでは colour。"],
    ["model", "機種・モデル", "名詞", "This is our most popular model.", "こちらが一番人気のモデルです。"],
    ["limited edition", "限定版", "名詞", "This is a limited edition color.", "こちらは限定カラーです。"],
    ["display model", "展示品", "名詞", "This is the display model.", "こちらは展示品です。"],
    ["brand-new", "新品の", "形容詞", "We'll give you a brand-new one.", "新品をお渡しします。"],
    ["warranty", "保証", "名詞", "It comes with a one-year warranty.", "1年間の保証が付いています。"],
    ["instruction manual", "取扱説明書", "名詞", "The instruction manual is also in English.", "取扱説明書は英語版もございます。"],
    ["sold separately", "別売り", "フレーズ", "The rain cover is sold separately.", "レインカバーは別売りです。"],
    ["gift wrapping", "ギフト包装", "名詞", "Would you like gift wrapping?", "ギフト包装はいかがなさいますか？"],
    ["delivery", "配達", "名詞", "We can deliver it to your hotel.", "ホテルまでお届けできます。"],
    ["ship overseas", "海外へ発送する", "フレーズ", "I'm sorry, we can't ship overseas.", "申し訳ございません、海外発送は承っておりません。"],
    ["exchange", "交換", "名詞", "We can do an exchange within one week.", "1週間以内なら交換できます。"],
    ["refund", "返金", "名詞", "I'm sorry, we can't give a refund.", "申し訳ございませんが、返金はできかねます。"],
  ]},
  { id:"phrase", kind:"phrase", icon:"💬", name:"接客のひと言", desc:"まずはこれだけ言えればOK", items:[
    ["Hello! Welcome.", "いらっしゃいませ。", "目を見て笑顔で「Hello!」と言うのが自然です。"],
    ["Please take your time.", "ごゆっくりご覧ください。"],
    ["Are you looking for anything in particular?", "何かお探しですか？"],
    ["How old is your baby?", "お子さまは何か月（何歳）ですか？"],
    ["How will you mainly use it?", "主にどんな場面で使う予定ですか？"],
    ["I'd recommend this one.", "こちらがおすすめです。"],
    ["Would you like to try it?", "試してみますか？"],
    ["Let me show you how to fold it.", "たたみ方をお見せしますね。"],
    ["Let me check if we have it in stock.", "在庫を確認いたします。"],
    ["Just a moment, please.", "少々お待ちください。"],
    ["Sorry, could you say that again?", "すみません、もう一度おっしゃっていただけますか？"],
    ["Could you speak a little more slowly?", "もう少しゆっくり話していただけますか？"],
    ["You can buy it tax-free.", "免税でお買い求めいただけます。"],
    ["May I see your passport, please?", "パスポートを拝見してもよろしいですか？"],
    ["How would you like to pay?", "お支払い方法はいかがなさいますか？"],
    ["Here's your receipt.", "レシートでございます。"],
    ["What a cute baby!", "かわいい赤ちゃんですね！"],
    ["Does that make sense?", "おわかりいただけましたか？", "「Do you understand?」は上から目線に聞こえることがあるので、こちらが無難です。"],
    ["Thank you very much.", "ありがとうございました。"],
    ["Have a nice trip!", "よいご旅行を！"],
  ]},
];
